version: '3'

services:
  web:
    stdin_open: true
    tty: true
    container_name: web-sota-conversion
    build:
      context: ..
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - /app/node_modules

