singleQuote: true
trailingComma: "all"
semi: false
tabWidth: 2
printWidth: 120
bracketSpacing: true
arrowParens: "avoid"
bracketSameLine: true
insertPragma: false
htmlWhitespaceSensitivity: "strict"
endOfLine: "lf"
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrder: ["<THIRD_PARTY_MODULES>", "^src/(.*)$", "^[./]"]
importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"]
